# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# CMAKE_REQUIRE_LARGE_FILE_SUPPORT
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set CMAKE_REQUIRE_LARGE_FILE_SUPPORT to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# CMAKE_REQUIRE_LARGE_FILE_SUPPORT__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set CMAKE_REQUIRE_LARGE_FILE_SUPPORT__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The HAVE_CMAKE_REQUIRE_LARGE_FILE_SUPPORT variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/marc/tmp/yocto/build/qemux86/tmp/work/i586-poky-linux/vtk/6.1.0-r1/build/CMakeFiles/CMakeTmp/src.cxx
# Executable    : /home/marc/tmp/yocto/build/qemux86/tmp/work/i586-poky-linux/vtk/6.1.0-r1/build/CMakeFiles/cmTryCompileExec2338853426-CMAKE_REQUIRE_LARGE_FILE_SUPPORT
# Run arguments : 
#    Called from: [1]	/home/marc/tmp/yocto/build/qemux86/tmp/work/i586-poky-linux/vtk/6.1.0-r1/VTK-6.1.0/CMakeLists.txt

SET( CMAKE_REQUIRE_LARGE_FILE_SUPPORT 
     "1"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( CMAKE_REQUIRE_LARGE_FILE_SUPPORT__TRYRUN_OUTPUT 
     "PLEASE_FILL_OUT-NOTFOUND"
     CACHE STRING "Output from TRY_RUN" FORCE)


# VTK_TYPE_CHAR_IS_SIGNED
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set VTK_TYPE_CHAR_IS_SIGNED to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# The VTK_TYPE_CHAR_IS_SIGNED_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/marc/tmp/yocto/build/qemux86/tmp/work/i586-poky-linux/vtk/6.1.0-r1/VTK-6.1.0/CMake/vtkTestCharSignedness.cxx
# Executable    : /home/marc/tmp/yocto/build/qemux86/tmp/work/i586-poky-linux/vtk/6.1.0-r1/build/CMakeFiles/cmTryCompileExec2063669875-VTK_TYPE_CHAR_IS_SIGNED
# Run arguments : 
#    Called from: [2]	/home/marc/tmp/yocto/build/qemux86/tmp/work/i586-poky-linux/vtk/6.1.0-r1/VTK-6.1.0/CMake/vtkTestTypes.cmake
#                 [1]	/home/marc/tmp/yocto/build/qemux86/tmp/work/i586-poky-linux/vtk/6.1.0-r1/VTK-6.1.0/CMakeLists.txt

SET( VTK_TYPE_CHAR_IS_SIGNED 
     "1"
     CACHE STRING "Result from TRY_RUN" FORCE)


# VTK_ANSI_STREAM_EOF_RESULT
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set VTK_ANSI_STREAM_EOF_RESULT to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# The VTK_ANSI_STREAM_EOF_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/marc/tmp/yocto/build/qemux86/tmp/work/i586-poky-linux/vtk/6.1.0-r1/build/CMake/vtkTestStreamEOF.cxx
# Executable    : /home/marc/tmp/yocto/build/qemux86/tmp/work/i586-poky-linux/vtk/6.1.0-r1/build/CMakeFiles/cmTryCompileExec2673137992-VTK_ANSI_STREAM_EOF_RESULT
# Run arguments : 
#    Called from: [2]	/home/marc/tmp/yocto/build/qemux86/tmp/work/i586-poky-linux/vtk/6.1.0-r1/VTK-6.1.0/CMake/vtkTestStreamsLibrary.cmake
#                 [1]	/home/marc/tmp/yocto/build/qemux86/tmp/work/i586-poky-linux/vtk/6.1.0-r1/VTK-6.1.0/CMakeLists.txt

SET( VTK_ANSI_STREAM_EOF_RESULT 
     "1"
     CACHE STRING "Result from TRY_RUN" FORCE)


# KWSYS_LFS_WORKS
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set KWSYS_LFS_WORKS to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# KWSYS_LFS_WORKS__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set KWSYS_LFS_WORKS__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The KWSYS_LFS_WORKS_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/marc/tmp/yocto/build/qemux86/tmp/work/i586-poky-linux/vtk/6.1.0-r1/VTK-6.1.0/Utilities/KWSys/vtksys/kwsysPlatformTestsCXX.cxx
# Executable    : /home/marc/tmp/yocto/build/qemux86/tmp/work/i586-poky-linux/vtk/6.1.0-r1/build/CMakeFiles/cmTryCompileExec3957435352-KWSYS_LFS_WORKS
# Run arguments : 
#    Called from: [1]	/home/marc/tmp/yocto/build/qemux86/tmp/work/i586-poky-linux/vtk/6.1.0-r1/VTK-6.1.0/Utilities/KWSys/vtksys/CMakeLists.txt

SET( KWSYS_LFS_WORKS 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( KWSYS_LFS_WORKS__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# KWSYS_CHAR_IS_SIGNED
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set KWSYS_CHAR_IS_SIGNED to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# KWSYS_CHAR_IS_SIGNED__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set KWSYS_CHAR_IS_SIGNED__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The KWSYS_CHAR_IS_SIGNED_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/marc/tmp/yocto/build/qemux86/tmp/work/i586-poky-linux/vtk/6.1.0-r1/VTK-6.1.0/Utilities/KWSys/vtksys/kwsysPlatformTestsCXX.cxx
# Executable    : /home/marc/tmp/yocto/build/qemux86/tmp/work/i586-poky-linux/vtk/6.1.0-r1/build/CMakeFiles/cmTryCompileExec1391951795-KWSYS_CHAR_IS_SIGNED
# Run arguments : 
#    Called from: [1]	/home/marc/tmp/yocto/build/qemux86/tmp/work/i586-poky-linux/vtk/6.1.0-r1/VTK-6.1.0/Utilities/KWSys/vtksys/CMakeLists.txt

SET( KWSYS_CHAR_IS_SIGNED 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( KWSYS_CHAR_IS_SIGNED__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)

