/* Generated automatically by H5make_libsettings -- do not edit */



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF5.  The full HDF5 copyright notice, including     *
 * terms governing use, modification, and redistribution, is contained in    *
 * the files COPYING and Copyright.html.  COPYING can be found at the root   *
 * of the source code distribution tree; Copyright.html can be found at the  *
 * root level of an installed copy of the electronic HDF5 document set and   *
 * is linked from the top-level documents page.  It can also be found at     *
 * http://hdfgroup.org/HDF5/doc/Copyright.html.  If you do not have          *
 * access to either file, you may request a copy from help@hdfgroup.org.     *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 * Created:		Apr 15, 2014
 *			root <root@qemuarm>
 *
 * Purpose:		This machine-generated source code contains
 *			information about the library build configuration
 *
 * Modifications:
 *
 *	DO NOT MAKE MODIFICATIONS TO THIS FILE!
 *	It was generated by code in `H5make_libsettings.c'.
 *
 *-------------------------------------------------------------------------
 */

char H5libhdf5_settings[]=
	"	    SUMMARY OF THE HDF5 CONFIGURATION\n"
	"	    =================================\n"
	"\n"
	"General Information:\n"
	"-------------------\n"
	"		   HDF5 Version: 1.8.12\n"
	"		  Configured on: Tue Apr 15 13:29:04 UTC 2014\n"
	"		  Configured by: root@qemuarm\n"
	"		 Configure mode: production\n"
	"		    Host system: armv5tejl-unknown-linux-gnueabi\n"
	"	      Uname information: Linux qemuarm 3.14.0-yocto-standard #1 PREEMPT Mon Apr 14 15:54:51 EDT 2014 armv5tejl GNU/Linux\n"
	"		       Byte sex: little-endian\n"
	"		      Libraries: shared\n"
	"	     Installation point: /home/root/hdf5-1.8.12/hdf5\n"
	"\n"
	"Compiling Options:\n"
	"------------------\n"
	"               Compilation Mode: production\n"
	"                     C Compiler: /usr/bin/gcc\n"
	"                         CFLAGS: \n"
	"                      H5_CFLAGS:  \n"
	"                      AM_CFLAGS: \n"
	"                       CPPFLAGS: \n"
	"                    H5_CPPFLAGS: -D_POSIX_C_SOURCE=199506L   -DNDEBUG -UH5_DEBUG_API\n"
	"                    AM_CPPFLAGS: -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_BSD_SOURCE \n"
	"               Shared C Library: yes\n"
	"               Static C Library: no\n"
	"  Statically Linked Executables: no\n"
	"                        LDFLAGS: \n"
	"                     H5_LDFLAGS: \n"
	"                     AM_LDFLAGS: \n"
	" 	 	Extra libraries:  -lz -ldl -lm \n"
	" 		       Archiver: ar\n"
	" 		 	 Ranlib: ranlib\n"
	" 	      Debugged Packages: \n"
	"		    API Tracing: no\n"
	"\n"
	"Languages:\n"
	"----------\n"
	"                        Fortran: no\n"
	"\n"
	"                            C++: no\n"
	"\n"
	"Features:\n"
	"---------\n"
	"                  Parallel HDF5: no\n"
	"             High Level library: yes\n"
	"                   Threadsafety: no\n"
	"            Default API Mapping: v18\n"
	" With Deprecated Public Symbols: yes\n"
	"         I/O filters (external): deflate(zlib)\n"
	"         I/O filters (internal): shuffle,fletcher32,nbit,scaleoffset\n"
	"                            MPE: no\n"
	"                     Direct VFD: no\n"
	"                        dmalloc: no\n"
	"Clear file buffers before write: yes\n"
	"           Using memory checker: no\n"
	"         Function Stack Tracing: no\n"
	"                           GPFS: no\n"
	"      Strict File Format Checks: no\n"
	"   Optimization Instrumentation: no\n"
	"       Large File Support (LFS): yes\n"
;

